### PR TITLE
Issue4 and architecture fixes

### LINKED ISSUE #338: Trail of Bits audit - Issue #4 (Flawed regex in tauri.conf.json)
our current regex  `"open": "[/subspace\\-desktop/]",` will accept any character existing in `subspace-desktop` string. This is not we want. 

Ultimately, we shouldn't enable this, and let backend do this work to not give frontend too much privilege

### PR DESCRIPTION
**Pull request by ozgunozerk**
We were using `shell.open()` on the frontend to open the log folder (via default OS file explorer). 
This was issue#4 from the audit. 

I made a backend function to handle this, and disabled `shell -> open` access for the frontend. This should fix #338 , and also help #339.

Along the way: 
- I fixed the typos and outdated stuff in the `architecture.md` file, this was mentioned in #340 , so we can complete that sub-task in that issue after this PR merges.
- fixed (9999 - 1000 + 1) 
- fixed weirdly named `checkDev()`
- Duplicate code for config creation

### CODE REVIEW

File: src/components/mainMenu.vue [hunk 1]
```diff
@@ -113,7 +113,7 @@ export default defineComponent({
       try {
         const log_path = await util.getLogPath();
         util.infoLogger('log path acquired:' + log_path);
-        await shell.open(log_path);
+        tauri.invoke("open_folder", {dir: log_path});
```
Comment (isSerge) [inline src/components/mainMenu.vue:116]: `invoke` is also async

File: src/lib/config.ts [hunk 2]
```diff
@@ -115,13 +115,6 @@ class Config {
    * @param {IConfig} - config object to store as config file
    */
   private async write(config: IConfig): Promise<void> {
```
Comment (isSerge) [inline src/lib/config.ts:117]: where do we create a directory instead?

File: src/components/mainMenu.vue (hunk 1 above)
Comment (ozgunozerk) [reply src/components/mainMenu.vue:116]: nice catch, thanks

File: src/lib/config.ts (hunk 2 above)
Comment (ozgunozerk) [reply src/lib/config.ts:117]: https://github.com/subspace/subspace-desktop/pull/342/files/4271bed595cb7af0703640e21551d7225adb2faf#diff-0b4f5977a52cef50ed20e7cdf9761795df9ee1cb3b5e5ea45edeb9394e8a47ffR65

here, trail of bits reported we are creating the config file in 2 different locations, so I kept the one in `init()`

File: src-tauri/src/utils.rs [hunk 3]
```diff
@@ -9,6 +10,27 @@ pub(crate) struct DiskStats {
     total_bytes: u64,
 }
 
+#[tauri::command]
+pub(crate) fn open_folder(dir: String) {
+    #[cfg(target_os = "windows")]
+    Command::new("explorer")
+        .arg(dir)
+        .spawn()
+        .expect("could not open to specified directory");
```
Comment (achiurizo) [inline src-tauri/src/utils.rs:19]:
```suggestion
        .expect("could not open the specified directory");
```

_very_ minor nitpick feel free to ignore 😄

**Review by achiurizo — APPROVED** [review]

File: src-tauri/src/utils.rs (hunk 3 above)
Comment (ozgunozerk) [reply src-tauri/src/utils.rs:19]: lemme fix that in the other pr, thanks for noticing that!
